### ISSUE TITLE
correctly handle rate stats

### ISSUE THREAD

**Issue by almartin82** [almartin82/projection_prep#22]
convert rate stats to counting before zscoring, per luke's point

**Comment by almartin82** [comment]
thinking out loud here -- @thecza @mcarter8:
converting rate to counting stats treats 'likes alike' -- it means that high BA / low playing time will be treated the same as high R per PA / low playing time.

but the general issue here is that low playing time guys are **always going to take a hit**, no matter how good their per-PA stats are.

the fact that steamer publishes both steamer and steamer600 suggests that there isn't a clear solution here... but if possible, I would like to get the 'correct' price for, say, a guy that is a platoon OF and is only expected to get 300 AB, but posts a 950 OPS on those AB because he murders lefties.

under the current scoring, that guy would almost certainly be a $1 guy.  but IRL you'd be willing to pay a couple of bucks for that.  

is there any way to quantify this?

**Comment by thecza** [comment]
This is another case where GP might be the way to go. Add pro-rated replacement-level stats to bring everyone up to 162 GP. That should ensure your platoon specialists stand out from the pool of players who are slightly-better than RL simply due to projected PAs.

**Comment by thecza** [comment]
player season value = player projected stats + ((162 – player_projectedGP)*(RepLev stats/game))
