### ISSUE TITLE
Unable to pull Steamer

### ISSUE THREAD

**Issue by jestarr** [almartin82/projection_prep#49]
I'm getting the following error message: "Error in names(df)[2] <- "fg_note" : 
  'names' attribute [2] must be the same length as the vector [1]"

**Comment by almartin82** [comment]
steamer data has probably changed how it returns since I wrote these functions!

**Comment by jestarr** [comment]
Any plans to update this package for 2018?

**Comment by almartin82** [comment]
I probably should!

**Comment by jestarr** [comment]
Anything :+1: ?

**Comment by almartin82** [comment]
Seems reasonable- can you look for the 2018 URL and post it here?

**Comment by almartin82** [comment]
okay, this was actually a fairly easy fix!  looks like fangraphs (rightly) pushes all traffic to `https`, but the html parser I am using is pretty old, and only handles `http` traffic.  the solution was an intermediate step where we read the content in using `RCurl::getURL` and then pass to `XML::readHTMLTable`.

Should probably move all of this to `rvest` / `httr`, which is the more current way of handling web content, but this seems to work for now.

**Comment by almartin82** [comment]
@jestarr let me know if this solves steamer / fangraphs for you.

**Comment by almartin82** [comment]
hmm now I get
```
Error in select_impl(.data, vars) : 
  found duplicated column name: , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , 
```

**Comment by almartin82** [comment]
issue is in `clean_raw_fangraphs`...

**Comment by jestarr** [comment]
It's taking forever to pull down any data using get_steamer.  Would rvest make the scrape quicker?  I wish Fangraphs had an open source API.

**Comment by almartin82** [comment]
It's pretty slow (5-10 min?) but it should resolve.

The scraping strategy was designed to be comprehensive but not fast. If
memory serves it traverses every team x every position - so there are a lot
of calls happening behind the scenes.
